config/routes.rb
Rails.application.routes.draw do
  get 'typing_game/index'
  devise_for :users
  resources :schedules, only: [:index, :create, :update, :destroy, :new, :show, :edit]
  resources :logs
  root 'home#index'
  get 'home/index'
  post '/save-log', to: 'logs#save_log'
  post '/save-active-window', to: 'logs#save_active_window'
  get '/typing_game', to: 'typing_game#index'
  get '/words/random_word', to: 'words#random_word'
  get 'products/fetch_and_save', to: 'products#fetch_and_save', as: 'fetch_and_save'
  post 'upload_excel', to: 'products#upload_excel'
  get '/products/show_result', to: 'products#show_result'
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :user
    validates :plan, presence: true
    validates :day, presence: true
    validates :time, presence: true
    validates :user_id, presence: true
    validates :start_time, presence: true
    validates :importance, presence: true
    
    def self.schedules_after_three_month
    # 今日から3ヶ月先までのデータを取得
    schedules = Schedule.all.where("day >= ?", Date.current).where("day < ?", Date.current >> 3).order(day: :desc)
    # 配列を作成し、データを格納
    # DBアクセスを減らすために必要なデータを配列にデータを突っ込んでます
    schedule_data = []
    schedules.each do |schedule|
      schedules_hash = {}
      schedules_hash.merge!(day: schedule.day.strftime("%Y-%m-%d"), time: schedule.time)
      schedule_data.push(schedules_hash)
    end
    schedule_data
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
    before_action :authenticate_user!  # Deviseの認証が必要な場合
  
  def index
    @schedule = Schedule.new(user_id: current_user.id)
    @schedules = current_user.schedules.where("day >= ?", Date.current).where("day < ?", Date.current >> 3).order(day: :desc)
  end

   def new
     @schedule = Schedule.new
     @day = params[:day]
     @time = params[:time]
     @start_time = DateTime.parse(@day + " " + @time + " " + "JST")
   end

   def show
     @schedule = Schedule.find(params[:id])
   end
   
  def edit
    @schedule = Schedule.find(params[:id])
  end


  def create
    # フォームから day と time を受け取り、starttime を生成
    times = params[:schedule][:time]
    success = true  # スケジュールの作成が成功したかどうかを示すフラグ
    year = params[:schedule]['day(1i)']
    month = params[:schedule]['day(2i)']
    day = params[:schedule]['day(3i)']
    selected_date = "#{year}-#{month}-#{day}"

    if selected_date.to_date <= Date.today
      success = false
      flash[:alert] = "過去の日付にスケジュールを作成することはできません"
    elsif times.nil? || times.empty?
      success = false
      flash[:alert] = "時間が選択されていません"
    else
      times.each do |time|
      start_datetime = Time.zone.parse("#{selected_date} #{time}")
      existing_schedule = Schedule.find_by(day: selected_date, time: time)
      
      @schedule = Schedule.new(schedule_params)  # @schedule オブジェクトを事前に初期化
      
      if existing_schedule
        # 既存のスケジュールが存在する場合、エラーメッセージを設定して処理を中止
        @schedule.errors.add(:base, "指定した日時には既に予定が存在します")
        success = false
      else
          # 既存のスケジュールが存在しない場合、新しいスケジュールを作成
        @schedule = Schedule.new(schedule_params)
        @schedule.start_time = start_datetime
        @schedule.time = time
        
        if !@schedule.valid?
          success = false  # 一つでもエラーがあれば success を false に設定
        end
      end
    end
    end

    if success
      # 全ての時間スロットが正常の場合の処理
      times.each do |time|
        start_datetime = Time.zone.parse("#{selected_date} #{time}")
        @schedule = Schedule.new(schedule_params)
        @schedule.start_time = start_datetime
        @schedule.time = time
        @schedule.save
      end
      flash[:notice] = "スケジュールが作成されました"
      redirect_to schedules_path
    else
      flash[:alert] = "スケジュールの作成に失敗しました"
      redirect_to schedules_path
    end
  end
  
def update
  @schedule = Schedule.find(params[:id])

  # スケジュールの更新が成功したかどうかを示すフラグ
  success = true

  if @schedule.update(schedule_params)
    flash[:notice] = "スケジュールが更新されました"
  else
    flash[:alert] = "スケジュールの更新に失敗しました"
    success = false
  end

  if success
    redirect_to schedules_path
  else
    render :edit
  end
end

 
 def destroy
     @schedule = Schedule.find(params[:id]) # スケジュールを見つけて設定する
     @schedule.destroy
	   flash[:notice] = "スケジュールを削除しました"
	   redirect_to schedules_path
 end
  
  private
    def schedule_params
      params.require(:schedule).permit(:plan, :day, :importance, :user_id, :time => [])
    end

  
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  def times
    times = [
      "一日の予定",
      "8:00",
      "8:30",
      "9:00",
             "9:30",
             "10:00",
             "10:30",
             "11:00",
             "11:30",
             "13:00",
             "13:30",
             "14:00",
             "15:00",
             "15:30",
             "16:00",
             "16:30",
             "17:30",
             "18:00",
             "18:30",
             "19:00",
             "19:30",
             "20:00"]
  end
  
  def check_schedule(schedules, day, time)
    result = false
    schedules_count = schedules.count
    # 取得した予約データにdayとtimeが一致する場合はtrue,一致しない場合はfalseを返します
    if schedules_count > 1
      schedules.each do |schedule|
        result = schedule[:day].eql?(day.strftime("%Y-%m-%d")) && schedule[:time].eql?(time)
        return result if result
      end
    elsif schedules_count == 1
      result = schedules[0][:day].eql?(day.strftime("%Y-%m-%d")) && schedules[0][:time].eql?(time)
      return result if result
    end
    return result
  end
  
def find_schedule(schedules, day, time)
  schedules.find { |schedule| schedule[:day] == day && schedule[:time] == time }
end

end

app/views/schedules/edit.html.erb
<% content_for :title do %>
  AWS-and-Rails-Portfolio Schedule edit
<% end %>

<% content_for :content do %>
<div class="container">
  <div class="row">
    <div class="col-12 text-center title">
      <h1>スケジュール詳細画面</h1>
    </div>
    <div class="col-12 mt-3 content">
      <%= form_for @schedule do |f| %>
        <div class="field row">
        <label for="plan">予定</label>
        <p><%= f.text_area :plan %></p>
        <label for="importance">重要度</label>
        <p>  <%= f.select :importance, [['低', '低'], ['中', '中'], ['高', '高']], {}, class: 'form-control' %></p>
      </div>
      <div class="actions row">
        <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.submit "スケジュール更新", class: "btn btn-sm btn-hachiss" %>
        </div>
      <% end %>
      <div class="col-12 text-right">
        <%= link_to '戻る', schedules_path %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/schedules/index.html.erb
<% content_for :title do %>
  AWS-and-Rails-Portfolio Schedule
<% end %>

<% content_for :content do %>
<div class="container-fluid">
  <h2 class="section-top"><span class="fas fa-dumbbell" aria-hidden="true"></span> Your Schedule</h2>
  <div class="col-md-3 col-sm-12 col-xs-12">
    <%= form_for @schedule, id: 'create-form' do |f| %>
      <div class="field row">
        <label for="plan">予定</label>
        <p><%= f.text_area :plan %></p>
        <label for="day">日付</label>
        <p><%= f.date_select :day %></p>
        <label for="time">時間</label>
        <p>
            <%= f.collection_check_boxes :time, [["8:00", "8:00"], ["8:30", "8:30"], ["9:00", "9:00"], ["9:30", "9:30"], ["10:00", "10:00"], ["10:30", "10:30"], ["11:00", "11:00"], ["11:30", "11:30"], ["12:00", "12:00"], ["12:30", "12:30"], ["13:00", "13:00"], ["13:30", "13:30"], ["14:00", "14:00"], ["14:30", "14:30"], ["15:00", "15:00"], ["15:30", "15:30"], ["16:00", "16:00"], ["16:30", "16:30"], ["17:00", "17:00"], ["17:30", "17:30"], ["18:00", "18:00"], ["18:30", "18:30"], ["19:00", "19:00"], ["19:30", "19:30"], ["20:00", "20:00"]], :last, :first, { include_hidden: false } do |b| %>
            <%= b.check_box %>
            <%= b.label %>
          <% end %>
        </p>
        <label for="importance">重要度</label>
        <p>  <%= f.select :importance, [['低', '低'], ['中', '中'], ['高', '高']], {}, class: 'form-control' %></p>
      </div>
      <div class="actions row">
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.submit "スケジュール作成", class: "btn btn-sm btn-hachiss" %>
      </div>
    <% end %>
  </div>
  <div class="col-md-9 col-sm-12 col-xs-12">
    <%= week_calendar events: @schedules do |date, schedules| %>
      <%= date.day %>
      <% schedules.each do |schedule| %>
        <div>
          <%= link_to schedule.plan, edit_schedule_path(schedule) %>
        </div>
      <% end %>
    <% end %>
    		<table class="schedule table table-bordered">
			<thead>
				<tr>
					<th>予定</th>
					<th>日付</th>
					<th>時間</th>
					<th>編集</th>
					<th>削除</th>
				</tr>
		  </thead>
			<% @schedules.each do |schedule| %>
				<tbody>
					<tr>
						<td><%= schedule.plan%></td>
						<td><%= schedule.day%></td>
						<td><%= schedule.start_time.in_time_zone("Tokyo").strftime("%Y-%m-%d %H:%M") %></td>
						<td><%=link_to "編集" , edit_schedule_path(schedule),:class=>"btn04"  %></td>
						<td><%=button_to "削除", schedule_path(schedule) , method: :delete , data: {confirm:"削除しますか"} ,:class=>"btn03"%></td>
					</tr>
				</tbody>
			<% end %>
  		</table>
  </div>
</div>
<% end %>

app/views/schedules/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center title">
      <h1>新規スケジュール入力画面</h1>
    </div>
    <div class="col-12 mt-3 content">
      <%= form_with model: @schedule, local: true, class: 'form' do |form| %>
      <%= render 'layouts/error_messages', model: form.object %>
      <div class="day form-group">
        <%= form.label :day, '日付' %>
        <%= form.text_field :day, class: 'form-control', value: @day, readonly: true %>
      </div>
      <div class="time form-group">
        <%= form.label :time, '時間' %>
        <%= form.text_field :time, class: 'form-control', value: @time, readonly: true %>
      </div>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.hidden_field :start_time, value: @start_time %>
      <div class="submit">
        <%= form.submit value: 'スケジュール作成', class: 'btn btn-primary mx-auto d-block' %>
      </div>
    <% end %>
    <div class="col-12 text-right">
      <%= link_to '戻る', schedules_path %>
    </div>
    </div>
  </div>
</div>

app/views/schedules/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center title">
      <h1>予約詳細画面</h1>
    </div>
    <div class="col-12 mt-3 text-center content">
      <div>
        <label><strong>日付：</strong></label>
        <p style="display:inline;"><%= @schedule.day %></p>
      </div>
      <div>
        <label><strong>時間：</strong></label>
        <p style="display:inline;"><%= @schedule.time %></p>
      </div>
    </div>
    <div class="col-12 text-right">
      <%= link_to '予約画面に戻る',schedules_path %>
    </div>
  </div>
</div>