config/routes.rb
Rails.application.routes.draw do
  get 'typing_game/index'
  devise_for :users
  resources :schedules, only: [:index, :create, :update, :destroy, :new, :show, :edit]
  resources :logs
  root 'home#index'
  get 'home/index'
  post '/save-log', to: 'logs#save_log'
  post '/save-active-window', to: 'logs#save_active_window'
  get '/typing_game', to: 'typing_game#index'
  get '/words/random_word', to: 'words#random_word'
  get 'products/fetch_and_save', to: 'products#fetch_and_save', as: 'fetch_and_save'
  post 'upload_excel', to: 'products#upload_excel'
  get '/products/show_result', to: 'products#show_result'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    date = Date.today
    @logs = current_user.logs.where(created_at: date.beginning_of_day..date.end_of_day)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :title do %>
  AWS-and-Rails-Portfolio Index
<% end %>
<meta name="csrf-token" content="<%= form_authenticity_token %>" />

<% content_for :content do %>
<h1>ログ情報</h1>
<p id="os-info"></p>
<p id="window-info"></p>

<%= pie_chart @logs.group(:log_message).count, library: { responsive: true } %>


<% if user_signed_in?%>

  <li>アプリケーション一覧</li>
  <li><%= link_to 'Schedule', schedules_path %></li>
  <li><%= link_to 'Typing', typing_game_path %></li>
  <li><%= link_to 'RakutenApiService', fetch_and_save_path %></li>
<% end %>

<br>

<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>

<% end %>